name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go:
          - 1.13.x
          - 1.14.x
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          sh script/libopus-install.sh
          go get -v -t -d ./...

      - name: Test
        run: go test -v ./...
